/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: mJqpyqbUtzd2VoHjhzzUXf

import { createUseGlobalVariants } from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariantszl2IwNtvPxZ6 } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: zl2IwNTVPxZ6/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariantszl2IwNtvPxZ6
});
