/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: mJqpyqbUtzd2VoHjhzzUXf
// Component: qT7hADdW03Jc

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import Button from "../../Button"; // plasmic-import: y61rLxDNYj2u/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: mJqpyqbUtzd2VoHjhzzUXf/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: mJqpyqbUtzd2VoHjhzzUXf/styleTokensProvider
import { _useStyleTokens as useStyleTokens_antd_5_hostless } from "../antd_5_hostless/PlasmicStyleTokensProvider"; // plasmic-import: ohDidvG9XsCeFumugENU3J/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: mJqpyqbUtzd2VoHjhzzUXf/projectcss
import sty from "./PlasmicStoryFrame.module.css"; // plasmic-import: qT7hADdW03Jc/css

import CheckSvgIcon from "./icons/PlasmicIcon__CheckSvg"; // plasmic-import: ep15jNBOwX87/icon
import ChevronUpSvgIcon from "./icons/PlasmicIcon__ChevronUpSvg"; // plasmic-import: dYTeiOOQJA1Q/icon
import ChevronDownSvgIcon from "./icons/PlasmicIcon__ChevronDownSvg"; // plasmic-import: bzrZ5Muri71Z/icon

createPlasmicElementProxy;

export type PlasmicStoryFrame__VariantMembers = {
  stage: "_1" | "_2" | "_3" | "_4";
};
export type PlasmicStoryFrame__VariantsArgs = {
  stage?: SingleChoiceArg<"_1" | "_2" | "_3" | "_4">;
};
type VariantPropType = keyof PlasmicStoryFrame__VariantsArgs;
export const PlasmicStoryFrame__VariantProps = new Array<VariantPropType>(
  "stage"
);

export type PlasmicStoryFrame__ArgsType = {
  stage2?: string;
  onStage2Change?: (val: string) => void;
};
type ArgPropType = keyof PlasmicStoryFrame__ArgsType;
export const PlasmicStoryFrame__ArgProps = new Array<ArgPropType>(
  "stage2",
  "onStage2Change"
);

export type PlasmicStoryFrame__OverridesType = {
  storyFrame?: Flex__<"div">;
};

export interface DefaultStoryFrameProps {
  stage2?: string;
  onStage2Change?: (val: string) => void;
  stage?: SingleChoiceArg<"_1" | "_2" | "_3" | "_4">;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicStoryFrame__RenderFunc(props: {
  variants: PlasmicStoryFrame__VariantsArgs;
  args: PlasmicStoryFrame__ArgsType;
  overrides: PlasmicStoryFrame__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "stage",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) =>
          (() => {
            try {
              return $state.stage2;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return undefined;
              }
              throw e;
            }
          })() ?? $props.stage
      },
      {
        path: "stage2",
        type: "writable",
        variableType: "text",

        valueProp: "stage2",
        onChangeProp: "onStage2Change"
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();
  const styleTokensClassNames_antd_5_hostless =
    useStyleTokens_antd_5_hostless();

  return (
    <div
      data-plasmic-name={"storyFrame"}
      data-plasmic-override={overrides.storyFrame}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        styleTokensClassNames_antd_5_hostless,
        sty.storyFrame,
        {
          [sty.storyFramestage__1]: hasVariant($state, "stage", "_1"),
          [sty.storyFramestage__4]: hasVariant($state, "stage", "_4")
        }
      )}
    >
      <Button
        className={classNames("__wab_instance", sty.button__dlvMp, {
          [sty.buttonstage__1__dlvMpFMek]: hasVariant($state, "stage", "_1"),
          [sty.buttonstage__4__dlvMp5GueA]: hasVariant($state, "stage", "_4")
        })}
        onClick={async event => {
          const $steps = {};

          $steps["updateStage2"] = true
            ? (() => {
                const actionArgs = {
                  variable: {
                    objRoot: $state,
                    variablePath: ["stage2"]
                  },
                  operation: 0,
                  value: ($state.stage2 =
                    $state.stage2 === "_1"
                      ? $state.stage2
                      : $state.stage2.replace(
                          /_(\d+)/,
                          (_, num) => `_${parseInt(num) - 1}`
                        ))
                };
                return (({ variable, value, startIndex, deleteCount }) => {
                  if (!variable) {
                    return;
                  }
                  const { objRoot, variablePath } = variable;

                  $stateSet(objRoot, variablePath, value);
                  return value;
                })?.apply(null, [actionArgs]);
              })()
            : undefined;
          if (
            $steps["updateStage2"] != null &&
            typeof $steps["updateStage2"] === "object" &&
            typeof $steps["updateStage2"].then === "function"
          ) {
            $steps["updateStage2"] = await $steps["updateStage2"];
          }
        }}
      />

      <div
        className={classNames(projectcss.all, sty.freeBox___6AxX, {
          [sty.freeBoxstage__1___6AxXFMek]: hasVariant($state, "stage", "_1"),
          [sty.freeBoxstage__4___6AxX5GueA]: hasVariant($state, "stage", "_4")
        })}
      >
        <ChevronUpSvgIcon
          className={classNames(projectcss.all, sty.svg__szaW, {
            [sty.svgstage__1__szaWFMek]: hasVariant($state, "stage", "_1")
          })}
          onClick={async event => {
            const $steps = {};

            $steps["updateStage2"] = true
              ? (() => {
                  const actionArgs = {
                    variable: {
                      objRoot: $state,
                      variablePath: ["stage2"]
                    },
                    operation: 0,
                    value: ($state.stage2 =
                      $state.stage2 === "_1"
                        ? $state.stage2
                        : $state.stage2.replace(
                            /_(\d+)/,
                            (_, num) => `_${parseInt(num) - 1}`
                          ))
                  };
                  return (({ variable, value, startIndex, deleteCount }) => {
                    if (!variable) {
                      return;
                    }
                    const { objRoot, variablePath } = variable;

                    $stateSet(objRoot, variablePath, value);
                    return value;
                  })?.apply(null, [actionArgs]);
                })()
              : undefined;
            if (
              $steps["updateStage2"] != null &&
              typeof $steps["updateStage2"] === "object" &&
              typeof $steps["updateStage2"].then === "function"
            ) {
              $steps["updateStage2"] = await $steps["updateStage2"];
            }
          }}
          role={"img"}
        />
      </div>
      <div
        className={classNames(projectcss.all, sty.freeBox__v2VMv, {
          [sty.freeBoxstage__1__v2VMvFMek]: hasVariant($state, "stage", "_1"),
          [sty.freeBoxstage__3__v2VMvDlUcg]: hasVariant($state, "stage", "_3")
        })}
      >
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text___2ZdHt,
            {
              [sty.textstage__1___2ZdHtFMek]: hasVariant($state, "stage", "_1"),
              [sty.textstage__2___2ZdHttytOq]: hasVariant(
                $state,
                "stage",
                "_2"
              ),
              [sty.textstage__3___2ZdHtDlUcg]: hasVariant(
                $state,
                "stage",
                "_3"
              ),
              [sty.textstage__4___2ZdHt5GueA]: hasVariant($state, "stage", "_4")
            }
          )}
        >
          {
            "\u062f\u0627\u0633\u062a\u0627\u0646 \u0627\u0644\u0645\u067e\u06cc\u0627\u062f"
          }
        </div>
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__gBz0O,
            {
              [sty.textstage__1__gBz0OFMek]: hasVariant($state, "stage", "_1"),
              [sty.textstage__2__gBz0OtytOq]: hasVariant($state, "stage", "_2"),
              [sty.textstage__3__gBz0ODlUcg]: hasVariant($state, "stage", "_3"),
              [sty.textstage__4__gBz0O5GueA]: hasVariant($state, "stage", "_4")
            }
          )}
        >
          {"\u062a\u0648\u0644\u062f \u06cc\u06a9 \u0631\u0648\u06cc\u0627\n"}
        </div>
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text___6WR3Q,
            {
              [sty.textstage__1___6WR3QFMek]: hasVariant($state, "stage", "_1"),
              [sty.textstage__2___6WR3QtytOq]: hasVariant(
                $state,
                "stage",
                "_2"
              ),
              [sty.textstage__3___6WR3QDlUcg]: hasVariant(
                $state,
                "stage",
                "_3"
              ),
              [sty.textstage__4___6WR3Q5GueA]: hasVariant($state, "stage", "_4")
            }
          )}
        >
          {hasVariant($state, "stage", "_4")
            ? "\u062f\u0631 \u062a\u06cc\u0631 \u0645\u0627\u0647 \u0633\u0627\u0644 1393 \u0627\u0648\u0644\u06cc\u0646 \u0642\u062f\u0645 \u0647\u0627"
            : hasVariant($state, "stage", "_3")
            ? "\u062f\u0631 \u062a\u06cc\u0631 \u0645\u0627\u0647 \u0633\u0627\u0644 1393 \u0627\u0648\u0644\u06cc\u0646 \u0642\u062f\u0645 \u0647\u0627"
            : hasVariant($state, "stage", "_2")
            ? "\u062f\u0631 \u062a\u06cc\u0631 \u0645\u0627\u0647 \u0633\u0627\u0644 1393 \u0627\u0648\u0644\u06cc\u0646 \u0642\u062f\u0645 \u0647\u0627"
            : "\u062f\u0631 \u062a\u06cc\u0631 \u0645\u0627\u0647 \u0633\u0627\u0644 1393 \u0627\u0648\u0644\u06cc\u0646 \u0642\u062f\u0645 \u0647\u0627 ."}
        </div>
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__zWcUp,
            {
              [sty.textstage__1__zWcUpFMek]: hasVariant($state, "stage", "_1"),
              [sty.textstage__2__zWcUPtytOq]: hasVariant($state, "stage", "_2"),
              [sty.textstage__3__zWcUpDlUcg]: hasVariant($state, "stage", "_3"),
              [sty.textstage__4__zWcUp5GueA]: hasVariant($state, "stage", "_4")
            }
          )}
        >
          {
            "\n\u0628\u0631\u0627\u06cc \u0631\u0642\u0645 \u0632\u062f\u0646 \u0631\u0648\u06cc\u0627\u06cc\u06cc \u0646\u0648 \u062f\u0631 \u0634\u0647\u0631 \u0627\u06cc\u0644\u0627\u0645 \u0628\u0631\u062f\u0627\u0634\u062a\u06cc\u0645."
          }
        </div>
      </div>
      <div
        className={classNames(projectcss.all, sty.freeBox___1Gard, {
          [sty.freeBoxstage__1___1GardFMek]: hasVariant($state, "stage", "_1"),
          [sty.freeBoxstage__4___1Gard5GueA]: hasVariant($state, "stage", "_4")
        })}
      >
        <ChevronDownSvgIcon
          className={classNames(projectcss.all, sty.svg__vq7Rv, {
            [sty.svgstage__4__vq7Rv5GueA]: hasVariant($state, "stage", "_4")
          })}
          onClick={async event => {
            const $steps = {};

            $steps["updateStage2"] = true
              ? (() => {
                  const actionArgs = {
                    variable: {
                      objRoot: $state,
                      variablePath: ["stage2"]
                    },
                    operation: 0,
                    value: ($state.stage2 =
                      $state.stage2 === "_4"
                        ? $state.stage2
                        : $state.stage2.replace(
                            /_(\d+)/,
                            (_, num) => `_${parseInt(num) + 1}`
                          ))
                  };
                  return (({ variable, value, startIndex, deleteCount }) => {
                    if (!variable) {
                      return;
                    }
                    const { objRoot, variablePath } = variable;

                    $stateSet(objRoot, variablePath, value);
                    return value;
                  })?.apply(null, [actionArgs]);
                })()
              : undefined;
            if (
              $steps["updateStage2"] != null &&
              typeof $steps["updateStage2"] === "object" &&
              typeof $steps["updateStage2"].then === "function"
            ) {
              $steps["updateStage2"] = await $steps["updateStage2"];
            }
          }}
          role={"img"}
        />
      </div>
      <Button
        className={classNames("__wab_instance", sty.button__wo2FR, {
          [sty.buttonstage__1__wo2FRFMek]: hasVariant($state, "stage", "_1"),
          [sty.buttonstage__4__wo2FR5GueA]: hasVariant($state, "stage", "_4")
        })}
        onClick={async event => {
          const $steps = {};

          $steps["updateStage2"] = true
            ? (() => {
                const actionArgs = {
                  variable: {
                    objRoot: $state,
                    variablePath: ["stage2"]
                  },
                  operation: 0,
                  value: ($state.stage2 =
                    $state.stage2 === "_4"
                      ? $state.stage2
                      : $state.stage2.replace(
                          /_(\d+)/,
                          (_, num) => `_${parseInt(num) + 1}`
                        ))
                };
                return (({ variable, value, startIndex, deleteCount }) => {
                  if (!variable) {
                    return;
                  }
                  const { objRoot, variablePath } = variable;

                  $stateSet(objRoot, variablePath, value);
                  return value;
                })?.apply(null, [actionArgs]);
              })()
            : undefined;
          if (
            $steps["updateStage2"] != null &&
            typeof $steps["updateStage2"] === "object" &&
            typeof $steps["updateStage2"].then === "function"
          ) {
            $steps["updateStage2"] = await $steps["updateStage2"];
          }
        }}
      />
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  storyFrame: ["storyFrame"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  storyFrame: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicStoryFrame__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicStoryFrame__VariantsArgs;
    args?: PlasmicStoryFrame__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicStoryFrame__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicStoryFrame__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicStoryFrame__ArgProps,
          internalVariantPropNames: PlasmicStoryFrame__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicStoryFrame__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "storyFrame") {
    func.displayName = "PlasmicStoryFrame";
  } else {
    func.displayName = `PlasmicStoryFrame.${nodeName}`;
  }
  return func;
}

export const PlasmicStoryFrame = Object.assign(
  // Top-level PlasmicStoryFrame renders the root element
  makeNodeComponent("storyFrame"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicStoryFrame
    internalVariantProps: PlasmicStoryFrame__VariantProps,
    internalArgProps: PlasmicStoryFrame__ArgProps
  }
);

export default PlasmicStoryFrame;
/* prettier-ignore-end */
